name: Node CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Node 16
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: "yarn"

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn run build

    - name: Linting
      run: yarn run lint

    - name: Jest Testing
      run: yarn run test

    - name: Test Coverage
      run: yarn run test:coverage
